backend:
  name: github
  repo: sonjishashank/salins-optic-web
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"
publish_mode: editorial_workflow

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/content/home.json"
        fields:
          - { label: "Hero Section - Title Line 1", name: "hero_title1", widget: "string", default: "Excellence in" }
          - { label: "Hero Section - Title Line 2 (Primary Color)", name: "hero_title2_primary", widget: "string", default: "Optometric Education" }
          - { label: "Hero Section - Subtitle", name: "hero_subtitle", widget: "text", default: "Discover your potential at S. Salins College of Optometry, where we shape the future of eye care professionals through innovative education and hands-on experience." }
          - { label: "Hero Section - Apply Now Button Text", name: "hero_apply_button_text", widget: "string", default: "Apply Now" }
          - { label: "Hero Section - Apply Now Button Link", name: "hero_apply_button_link", widget: "string", default: "https://docs.google.com/forms/d/e/1FAIpQLSfrKremrqPjDh5O_o9GrJ60qdIq4d9LjIJ30IDe-Ar9YrQchw/viewform?usp=sharing" }
          - { label: "Hero Section - Learn More Button Text", name: "hero_learn_more_button_text", widget: "string", default: "Learn More" }
          - { label: "Hero Section - Learn More Button Link", name: "hero_learn_more_button_link", widget: "string", default: "/admission" }
          - { label: "Hero Section - Spline Scene URL", name: "hero_spline_url", widget: "string", default: "https://prod.spline.design/EXUCiceuP8odg10J/scene.splinecode" }

          - { label: "About Section - Title Line 1", name: "about_title1", widget: "string" }
          - { label: "About Section - Title Line 2 (Primary Color)", name: "about_title2_primary", widget: "string" }
          - { label: "About Section - Text", name: "about_text", widget: "markdown" }
          - { label: "About Section - Image", name: "about_image", widget: "image" }

          - { label: "Programs Section - Title Line 1", name: "programs_title1", widget: "string" }
          - { label: "Programs Section - Title Line 2 (Primary Color)", name: "programs_title2_primary", widget: "string" }
          - { label: "Programs Section - Description", name: "programs_description", widget: "text" }
          - label: "Programs List"
            name: "programs_list"
            widget: "list"
            fields:
              - { label: "Icon", name: "icon", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Duration", name: "duration", widget: "string" }

      - label: "Admission Page"
        name: "admission"
        file: "src/content/admission.json"
        fields:
          - { label: "Hero Section - Title Line 1", name: "hero_title1", widget: "string" }
          - { label: "Hero Section - Title Line 2 (Primary Color)", name: "hero_title2_primary", widget: "string" }
          - { label: "Hero Section - Subtitle", name: "hero_subtitle", widget: "text" }
          
          - label: "Eligibility Requirements"
            name: "eligibility_requirements"
            widget: "list"
            fields:
              - { label: "Program", name: "program", widget: "string" }
              - { label: "Requirements", name: "requirements", widget: "list" }
              - { label: "Duration", name: "duration", widget: "string" }
              - { label: "Intake", name: "intake", widget: "string" }

          - label: "Admission Steps"
            name: "admission_steps"
            widget: "list"
            fields:
              - { label: "Step Number", name: "step", widget: "number" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Icon", name: "icon", widget: "string" }
              - { label: "Timeline", name: "timeline", widget: "string" }

      - label: "Events Page"
        name: "events"
        file: "src/content/events.json"
        fields:
          - { label: "Hero Section - Title Line 1", name: "hero_title1", widget: "string" }
          - { label: "Hero Section - Title Line 2 (Primary Color)", name: "hero_title2_primary", widget: "string" }
          - { label: "Hero Section - Subtitle", name: "hero_subtitle", widget: "text" }

          - label: "Upcoming Events"
            name: "upcoming_events"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Date", name: "date", widget: "datetime" }
              - { label: "Location", name: "location", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Type", name: "type", widget: "select", options: ["Conference", "Academic", "Workshop", "Other"] }
              - { label: "Registration Link", name: "registration_link", widget: "string", required: false }

          - label: "Past Event Images"
            name: "past_event_images"
            widget: "list"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }

      - label: "Contact Page"
        name: "contact"
        file: "src/content/contact.json"
        fields:
          - label: "Contact Information"
            name: "contact_info"
            widget: "list"
            fields:
              - { label: "Icon", name: "icon", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Details", name: "details", widget: "list" }
              - { label: "Color", name: "color", widget: "string" }

          - label: "Social Links"
            name: "social_links"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Icon", name: "icon", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              - { label: "Color", name: "color", widget: "string" }

      - label: "Management Page"
        name: "management"
        file: "src/content/management.json"
        fields:
          - label: "Principal"
            name: "principal"
            widget: "object"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Qualification", name: "qualification", widget: "string" }
              - { label: "Experience", name: "experience", widget: "string" }
              # - { label: "Email", name: "email", widget: "string" }
              # - { label: "Phone", name: "phone", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Bio", name: "bio", widget: "text" }
              - { label: "Achievements", name: "achievements", widget: "list" }

          - label: "Faculty Heads"
            name: "faculty_heads"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Qualification", name: "qualification", widget: "string" }
              # - { label: "Specialization", name: "specialization", widget: "string" }
              # - { label: "Email", name: "email", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
